### ISSUE TITLE
When calling HorizontalCalendar.selectDate(date, true), HorizontalCalendarListener's onDateSelected is not called.

### ISSUE THREAD

**Issue by TheIronMarx** [Mulham-Raee/Horizontal-Calendar#20]
The key factor here is the `true` `immediate` argument. When false, it does it's thing animating to the date given and calls the `HorizontalCalendarListener`'s callback. When true, it immediately shifts the `HorizontalCalendarView` but does not invoke the callback.

on 1.1.5

**Comment by Mulham-Raee** [comment]
Hello @TheIronMarx 

Thanks for pointing this out, I see where this problem might come from, since callbacks are related to scroll or click events, it will not be called in case of selecting a date with `immediate` parameter set to `true`.
I will definitely change this in the next release, but if it's an urgent feature for you I suggest that you clone the library and adopt it to your needs, a pull request is always welcomed :)

Best Regards

**Comment by TheIronMarx** [comment]
Thanks for responding!
I do consider this fairly urgent.
I will attempt to fix and submit a PR this weekend unless you plan to fix and release before hand.
If I do successfully fix it, would you consider releasing an update immediately?

**Comment by Mulham-Raee** [comment]
@TheIronMarx 

Yeah sure, unless it is not a very efficient fix :)

**Comment by Mulham-Raee** [comment]
fixed #24
